const TypsFiltrs = {
  Industry: [
    "BI-отчеты",
    "Гос. заказ",
    "Энергетика",
    "Образование",
    "Финтех",
    "Образ жизни",
    "Медицина",
    "E-commerce",
    "Безопасность",
    "Развлечения",
    "Картография",
  ],
  Platforms: [
    "Android",
    "Chat-system",
    "Telegram",
    "Backend",
    "Windows",
    "Панель управления",
    "Web",
    "iOS",
  ],
  Services: [
    "Релиз",
    "Сопровождение",
    "Дизайн",
    "Тестирование",
    "Разработка",
    "Предпроектная деятельность",
    "Аналитика",
    "Приемка",
  ],
  Languages: [
    "Node.JS",
    "Java",
    "Xamarin",
    "Wordpress",
    "Drupal 8, Angular",
    "ASP.NET Core, Azure",
    "MS Power BI",
    "1C-Битрикс",
    "Objective-C",
    "C#, UWP",
    "Python",
    "PHP",
    "Kotlin",
    "MODX",
    "Swift",
    "PhoneGap",
    "React",
    "Java, Kotlin",
    "Cordova",
    "C++",
  ],
};

export default TypsFiltrs;
